services:
  taxi.api:
    ports:
      - "5001:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=TaxiDb;Username=postgres;Password=YourStrong@Password1
      OTEL_EXPORTER_OTLP_ENDPOINT: http://seq:5341/ingest/otlp/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    restart: on-failure

  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong@Password1
      POSTGRES_DB: TaxiDb
    ports:
      - "5433:5432"
    restart: always

  seq:
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:5341"
      - "8081:80"
    restart: unless-stopped

  prometheus:
    ports:
      - "9090:9090"
    restart: unless-stopped

  grafana:
    environment:
      GF_SECURITY_ADMIN_PASSWORD: YourStrongPwd
    ports:
      - "3000:3000"
    restart: unless-stopped
