services:
  taxi.api:
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=TaxiDb;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      JwtSettings__Secret: ${JWT_SECRET}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://seq:5341/ingest/otlp/v1/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    restart: always

  postgres:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: TaxiDb
    restart: always

  seq:
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: "false"
    restart: always

  prometheus:
    restart: always

  grafana:
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    restart: always
