<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>c8875f69-57f4-402e-9cb8-bdc10fb5c99a</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Asp.Versioning.Mvc" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
        <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="My.Extensions.Localization.Json" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Taxi.Client\Taxi.Client.csproj" />
        <ProjectReference Include="..\Taxi.Application\Taxi.Application.csproj" />
        <ProjectReference Include="..\Taxi.Contracts\Taxi.Contracts.csproj" />
        <ProjectReference Include="..\Taxi.Infrastructure\Taxi.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Content Update="Resources\SharedResource.en.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="Resources\SharedResource.ar.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="Resources\SharedResource.nl.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="Resources\SharedResource.de.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="Resources\SharedResource.pl.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="Resources\SharedResource.uk.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="Resources\SharedResource.fr.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="Resources\SharedResource.es.json" CopyToOutputDirectory="PreserveNewest" />
        <Content Update="Resources\SharedResource.ro.json" CopyToOutputDirectory="PreserveNewest" />
        <None Include="Assets\Fonts\NotoSansArabic-Regular.ttf" CopyToOutputDirectory="PreserveNewest" />
        <None Include="Assets\Fonts\NotoSansArabic-Bold.ttf" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>

</Project>
